### ISSUE TITLE
Either use CDN or tailwind.config.js file

### ISSUE THREAD

**Issue by Tyler-Hilbert** [daishadavis/Personal-Website#2]
Currently this repo has both and you really only want one.
It's not a huge issue, but I'd like to document it so that it doesn't get lost and we can come back to fixing it later :)

**Comment by daishadavis** [comment]
Will do I'll Just focus on the cdn and get rid of the config file

**Comment by Tyler-Hilbert** [comment]
awesome!!!
run these commands:
git rm -rf node_modules
git rm .DS_STORE package-lock.json package.json tailwind.config.js
git commit -m "Deleted extra files"
git push

**Comment by daishadavis** [comment]
all done

**Comment by Tyler-Hilbert** [comment]
https://github.com/daishadavis/Personal-Website/commit/223c9e8e715ffcc5e9984d4aec0261c1d5e97958
