### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Tyler-Hilbert** [daishadavis/Personal-Website#3]
Can you link Wikipedia or Goodreads instead of Amazon lol.

**Comment by daishadavis** [comment]
Lol I can do Goodreads. Wikipedia doesn't have very accurate information.

@Tyler-Hilbert

**Comment by Tyler-Hilbert** [comment]
https://github.com/daishadavis/Personal-Website/commit/63aae7695ad0e7da4216d96f72071d2c76e58b12
