### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Tyler-Hilbert** [daishadavis/Personal-Website#5]
<img width="958" alt="Screenshot 2024-01-31 at 2 54 18 PM" src="https://github.com/daishadavis/Personal-Website/assets/6968707/aba8105a-428e-40c7-94e0-78f726551b82">

text at bottom

**Comment by daishadavis** [comment]
This is cool how did you do this?

@Tyler-Hilbert

**Comment by Tyler-Hilbert** [comment]
@daishadavis It's responsive mode design in Safari.


There is a mild responsive improvement here, but it's not perfect
https://github.com/Tyler-Hilbert/Daisha-Personal-Website/commit/d1d60aed7e6a82aa9759bc0cc4c5fa41b89a50c8

**Comment by Tyler-Hilbert** [comment]
Can we pretend I'm not hideous?
<img width="958" alt="Screenshot 2024-01-31 at 7 38 42 PM" src="https://github.com/daishadavis/Personal-Website/assets/6968707/28148a98-a518-42d0-a4da-548137742c78">

**Comment by daishadavis** [comment]
Your not hideous just a noob
