### ISSUE TITLE
More readable font

### ISSUE THREAD

**Issue by Tyler-Hilbert** [daishadavis/Personal-Website#6]
"It’s cool but I think the font is a bit tricky to read. Otherwise 👍"

I got that feedback XD

@daishadavis Is there a better font for this website??
https://github.com/Tyler-Hilbert/Daisha-Personal-Website/tree/3a82e40c0a1bc2afeb67ced5a16ad5682da33345

<img width="1501" alt="Screenshot 2024-02-16 at 2 09 13 PM" src="https://github.com/daishadavis/Personal-Website/assets/6968707/1b3022f4-aadc-4a58-a154-4255edd18f9f">

**Comment by daishadavis** [comment]
@Tyler-Hilbert I'll find one
